// Date: 6/23/2015 9:46:28 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.SpaceCraftTeam.SpaceCraft.renderer.model;

import com.SpaceCraftTeam.SpaceCraft.reference.Models;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraftforge.client.model.AdvancedModelLoader;
import net.minecraftforge.client.model.IModelCustom;

public class ModelWindmillBaseMeta0 extends ModelBase
{
    public IModelCustom modelWindmill;

    public ModelWindmillBaseMeta0() {
        modelWindmill = AdvancedModelLoader.loadModel(Models.MODELWINDMILLBASEMETA0);
    }

    public void render()
    {
        modelWindmill.renderAll();
    }

}
